name: CI workflow
# on – определяет события, которые запускают воркфлоу
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# jobs: Определяет рабочие задачи, которые необходимо выполнить.
jobs:
  build:
    # задача сборка проекта, выполняется на ubuntu
    runs-on: ubuntu-latest
    # steps: шаги, чтобы выполнить задачу
    steps:
       # Клонируем репозиторий
      - uses: actions/checkout@v4
      # Устанавливаем Node.js
      - uses: actions/setup-node@v4
      - run: make install
      - run: make build
      - run: make test

      - name: run lint
        run: make lint

      - name: start
        run: make start
